#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# Ruslan Agent — First-Boot Setup Script
# Runs inside the real Termux environment (ARM64 native)
# Installs all Python dependencies and configures the agent
# ============================================================

set -euo pipefail

HOME_DIR="$HOME"
LOG_FILE="$HOME_DIR/setup.log"
PREFIX="$PREFIX"

echo "=== Ruslan Agent Setup v1 ===" | tee "$LOG_FILE"
echo "Started: $(date)" | tee -a "$LOG_FILE"
echo "Prefix: $PREFIX" | tee -a "$LOG_FILE"
echo "Home: $HOME_DIR" | tee -a "$LOG_FILE"

# === Step 1: Check Python ===
echo "" | tee -a "$LOG_FILE"
echo "[1/4] Checking Python..." | tee -a "$LOG_FILE"
PYTHON=$(which python3 2>/dev/null || which python 2>/dev/null || echo "")
if [ -z "$PYTHON" ]; then
    echo "ERROR: Python not found!" | tee -a "$LOG_FILE"
    exit 1
fi
echo "Python: $($PYTHON --version 2>&1)" | tee -a "$LOG_FILE"

# === Step 2: Install pip packages ===
echo "" | tee -a "$LOG_FILE"
echo "[2/4] Installing pip packages..." | tee -a "$LOG_FILE"

# Upgrade pip first
$PYTHON -m pip install --upgrade pip 2>&1 | tee -a "$LOG_FILE"

# Install core dependencies
# httpx, pyyaml, python-dotenv are pure Python -> always work
# cryptography, pydantic have native extensions -> need aarch64 wheels
echo "Installing httpx..." | tee -a "$LOG_FILE"
$PYTHON -m pip install httpx 2>&1 | tee -a "$LOG_FILE"

echo "Installing PyYAML..." | tee -a "$LOG_FILE"
$PYTHON -m pip install pyyaml 2>&1 | tee -a "$LOG_FILE"

echo "Installing python-dotenv..." | tee -a "$LOG_FILE"
$PYTHON -m pip install python-dotenv 2>&1 | tee -a "$LOG_FILE"

echo "Installing pydantic..." | tee -a "$LOG_FILE"
$PYTHON -m pip install pydantic 2>&1 | tee -a "$LOG_FILE"

echo "Installing uvicorn..." | tee -a "$LOG_FILE"
$PYTHON -m pip install uvicorn 2>&1 | tee -a "$LOG_FILE"

# Try to install hermes-cli/ruslan-agent
echo "Installing ruslan-agent..." | tee -a "$LOG_FILE"
$PYTHON -m pip install ruslan-agent 2>&1 | tee -a "$LOG_FILE" || {
    echo "WARNING: ruslan-agent pip install failed, trying hermes-cli..." | tee -a "$LOG_FILE"
    $PYTHON -m pip install hermes-cli 2>&1 | tee -a "$LOG_FILE" || {
        echo "WARNING: Neither ruslan-agent nor hermes-cli found on PyPI" | tee -a "$LOG_FILE"
        echo "Installing from GitHub..." | tee -a "$LOG_FILE"
        $PYTHON -m pip install git+https://github.com/valldun1/ruslan.git 2>&1 | tee -a "$LOG_FILE" || {
            echo "WARNING: GitHub install failed too — will use local fallback" | tee -a "$LOG_FILE"
        }
    }
}

# Verify key packages
echo "" | tee -a "$LOG_FILE"
echo "Installed packages:" | tee -a "$LOG_FILE"
$PYTHON -m pip list 2>&1 | tee -a "$LOG_FILE"

# === Step 3: Create .env from template ===
echo "" | tee -a "$LOG_FILE"
echo "[3/4] Creating configuration..." | tee -a "$LOG_FILE"
if [ -f "$HOME_DIR/.env" ]; then
    echo ".env already exists, checking..." | tee -a "$LOG_FILE"
    # Ensure GATEWAY_URL is set
    if ! grep -q "GATEWAY_URL" "$HOME_DIR/.env"; then
        echo "GATEWAY_URL=http://127.0.0.1:9123" >> "$HOME_DIR/.env"
    fi
else
    cat > "$HOME_DIR/.env" << 'ENVEOF'
# Ruslan Agent — generated by setup
PROVIDER=opencode-go
MODEL=deepseek-v4-flash
GATEWAY_URL=http://127.0.0.1:9123
# Add your API key below:
# API_KEY=
ENVEOF
    echo "Created .env" | tee -a "$LOG_FILE"
fi

# === Step 4: Verify gateway ===
echo "" | tee -a "$LOG_FILE"
echo "[4/4] Verifying gateway..." | tee -a "$LOG_FILE"
if $PYTHON -c "import hermes_cli" 2>/dev/null; then
    echo "✓ hermes_cli is available" | tee -a "$LOG_FILE"
elif $PYTHON -c "import hermes" 2>/dev/null; then
    echo "✓ hermes is available" | tee -a "$LOG_FILE"
else
    echo "⚠ hermes module not found — will use generic gateway" | tee -a "$LOG_FILE"
fi

# Create marker file
touch "$HOME_DIR/.setup_complete"
echo "" | tee -a "$LOG_FILE"
echo "=== Setup Complete ===" | tee -a "$LOG_FILE"
echo "Completed: $(date)" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo "To start: hermes gateway run --port 9123" | tee -a "$LOG_FILE"
