package ru.valldun.ruslan

import android.content.Context
import android.content.SharedPreferences
import org.json.JSONArray
import org.json.JSONObject

/**
 * Manages provider configurations — stores in SharedPreferences as JSON
 */
class ProviderManager(context: Context) {

    private val prefs: SharedPreferences =
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun getAllProviders(): List<ProviderConfig> {
        val json = prefs.getString(KEY_PROVIDERS, null) ?: return emptyList()
        return try {
            val arr = JSONArray(json)
            (0 until arr.length()).map { i ->
                val obj = arr.getJSONObject(i)
                ProviderConfig(
                    id = obj.getString("id"),
                    name = obj.getString("name"),
                    apiKey = obj.optString("apiKey", ""),
                    baseUrl = obj.optString("baseUrl", ""),
                    defaultModel = obj.optString("defaultModel", ""),
                    isActive = obj.optBoolean("isActive", false)
                )
            }
        } catch (e: Exception) {
            emptyList()
        }
    }

    fun saveProviders(providers: List<ProviderConfig>) {
        val arr = JSONArray()
        providers.forEach { p ->
            arr.put(JSONObject().apply {
                put("id", p.id)
                put("name", p.name)
                put("apiKey", p.apiKey)
                put("baseUrl", p.baseUrl)
                put("defaultModel", p.defaultModel)
                put("isActive", p.isActive)
            })
        }
        prefs.edit().putString(KEY_PROVIDERS, arr.toString()).apply()
    }

    fun getActiveProvider(): ProviderConfig? {
        return getAllProviders().firstOrNull { it.isActive }
    }

    fun setActiveProvider(id: String) {
        val providers = getAllProviders().map { p ->
            p.copy(isActive = p.id == id)
        }
        saveProviders(providers)
    }

    fun addOrUpdateProvider(provider: ProviderConfig) {
        val providers = getAllProviders().toMutableList()
        val idx = providers.indexOfFirst { it.id == provider.id }
        if (idx >= 0) {
            providers[idx] = provider
        } else {
            providers.add(provider)
        }
        saveProviders(providers)
    }

    fun deleteProvider(id: String) {
        val providers = getAllProviders().filter { it.id != id }
        saveProviders(providers)
    }

    /**
     * Initialize with built-in providers if first launch
     */
    fun initDefaults() {
        if (prefs.getString(KEY_PROVIDERS, null) == null) {
            saveProviders(ProviderConfig.BUILT_IN)
        }
    }

    /**
     * Generate .env content for the active provider
     */
    fun generateEnvContent(): String {
        val active = getActiveProvider() ?: return ""
        val sb = StringBuilder()
        sb.appendLine("# Auto-generated by Ruslan Agent")
        sb.appendLine("PROVIDER=${active.id}")
        sb.appendLine("MODEL=${active.defaultModel}")
        if (active.apiKey.isNotEmpty()) {
            sb.appendLine("API_KEY=${active.apiKey}")
        }
        if (active.baseUrl.isNotEmpty()) {
            sb.appendLine("BASE_URL=${active.baseUrl}")
        }
        return sb.toString()
    }

    companion object {
        const val PREFS_NAME = "ruslan_providers"
        const val KEY_PROVIDERS = "provider_list"
    }
}
